revised
alg2021/gcd pull request #15
Opened 2021-06-12 10:10 UTC by kipomaro

2021-06-21 05:17 UTC, 17b17125 commented
名前 `Euclidean_gcd_rec` の関数の内容が講義資料でいう`Euclidean_gcd_itr`になっています

2021-06-21 09:14 UTC, 17b17125 requested changes

2021-06-21 09:14 UTC, 17b17125 commented on src/gcd.c
> +  return y;
```suggestion
  while(x != 0){
    unsigned int z = x;
     x = y % x;
     y = z;
  }
  return y;
```
Conversation に普通の投稿としてコメントしてしまいましたが，変更して push しなおす必要がある点なので request changes として投稿しなおします．

2021-06-21 09:57 UTC, kipomaro commented on src/gcd.c
> +  return y;
pushのやり方がわからないので教えてもらってもよろしいですか

2021-06-21 11:21 UTC, ryuhei-mori commented on src/gcd.c
> +  return y;
一回目に `push` したのと同様にしてください。覚えていなければ説明の動画を確認してください。 `git add` からやればいいです。

2021-06-22 04:06 UTC, 17b17125 commented
👍

2021-06-22 04:06 UTC, closed without merging