課題
alg2021/gcd pull request #9
Opened 2021-06-11 09:47 UTC by lion3d

よろしくお願いします

2021-06-17 23:35 UTC, yoshimuray requested changes

2021-06-17 23:35 UTC, yoshimuray commented on src/gcd.c
> +	bool euc_itr = true;
c言語にはbool型はないためここでコンパイルエラーが起きます。
修正したらまたpushして下さい。

2021-06-17 23:56 UTC, yoshimuray commented on src/gcd.c
> +	bool euc_itr = true;
ANSI C には bool 型はありませんが、この演習では C言語のバージョンについては柔軟に対応しますので、このまま修整しなくてよいです。

2021-06-21 08:21 UTC, 17b17125 commented
👍

2021-06-21 08:21 UTC, closed without merging